questions = [
    {"number": "1", "question": "Held hands, romantically?"},
     {"number": "2", "question": "Been on a date?"},
     {"number": "3", "question": "Been in a relationship?"},
     {"number": "4", "question": "Danced without leaving room for Jesus?Room for Jesus"},
     {"number": "5", "question": "Kissed a non-family member?"},
     {"number": "6", "question": "Kissed a non-family member on the lips?"},
     {"number": "7", "question": "French kissed?"},
     {"number": "8", "question": "French kissed in public?"},
     {"number": "9", "question": "Kissed on the neck?"},
     {"number": "10", "question": "Kissed horizontally?"},
     {"number": "11", "question": "Given or received a love bite?"},
     {"number": "12", "question": "Kissed or been kissed on the breast?"},
     {"number": "13", "question": "Kissed someone below the belt?"},
     {"number": "14", "question": "Kissed more than one person at a time?"},
     {"number": "15", "question": "Played a game involving stripping?"},
     {"number": "16", "question": "Masturbated to a picture or video?"},
     {"number": "17", "question": "Masturbated while someone else was in the room?"},
     {"number": "18", "question": "Helped someone masturbate?"},
     {"number": "19", "question": "Been caught masturbating?"},
     {"number": "20", "question": "Masturbated with an inanimate object?"},
     {"number": "21", "question": "Seen or read pornographic material?"},
     {"number": "22", "question": "Massaged or been massaged sensually?"},
     {"number": "23", "question": "Gone through the motions of intercourse whilst being fully dressed?"},
     {"number": "24", "question": "Undressed or been undressed by a MPS (member of the preferred sex)?"},
     {"number": "25", "question": "Showered with a MPS?"},
     {"number": "26", "question": "Fondled or had your butt cheeks fondled?"},
     {"number": "27", "question": "Fondled or had your breasts fondled?"},
     {"number": "28", "question": "Fondled or had your genitals fondled?"},
     {"number": "29", "question": "Heard of blue balls?"},
     {"number": "30", "question": "Had an orgasm due to someone else's manipulation?"},
     {"number": "31", "question": "Tried sexting with any stranger(s)?"},
     {"number": "32", "question": "Sent or received sexually explicit photographs?"},
     {"number": "33", "question": "Engaged in sexually explicit activity over video chat?"},
     {"number": "34", "question": "Cheated on a significant other during a relationship?"},
     {"number": "35", "question": "Purchased contraceptives?"}, {"number": "36", "question": "Given oral sex?"},
     {"number": "37", "question": "Received oral sex?"},
     {"number": "38", "question": "Ingested someone else's genital secretion?"},
     {"number": "39", "question": "Used a sex toy with a partner?"},
     {"number": "40", "question": "Spent the night with a MPS?"},
     {"number": "41", "question": "Been walked in on while engaging in a sexual act?"},
     {"number": "42", "question": "Kicked a roommate out to commit a sexual act?"},
     {"number": "43", "question": "Had sexual intercourse?"},
     {"number": "44", "question": "Had sexual intercourse three or more times in one night?"},
     {"number": "45", "question": "Had sexual intercourse ten or more times?"},
     {"number": "46", "question": "Had sexual intercourse in four or more different positions?"},
     {"number": "47", "question": "Had sexual intercourse with a stranger or person you met within 24 hours?"},
     {"number": "48", "question": "Had sexual intercourse in a motor vehicle?"},
     {"number": "49", "question": "Had sexual intercourse outdoors?"},
     {"number": "50", "question": "Had sexual intercourse in public?"},
     {"number": "51", "question": "Had sexual intercourse in a swimming pool or hot tub?"},
     {"number": "52", "question": "Had sexual intercourse in a bed not belonging to you or your partner?"},
     {"number": "53",
      "question": "Had sexual intercourse while you or your partner's parents were in the same home?"},
     {"number": "54", "question": "Had sexual intercourse with a non-participating third party in the same room?"},
     {"number": "55", "question": "Had a threesome?"}, {"number": "56", "question": "Attended an orgy?"},
     {"number": "57",
      "question": "Had two or more distinct acts of sexual intercourse with two or more people within 24 hours?"},
     {"number": "58", "question": "Had sexual intercourse with five or more partners?"},
     {"number": "59", "question": "Been photographed or filmed during sexual intercourse by yourself or others?"},
     {"number": "60", "question": "Had period sex?"}, {"number": "61", "question": "Had anal sex?"},
     {"number": "62", "question": "Had a pregnancy scare?"},
     {"number": "63", "question": "Impregnated someone or been impregnated?"},
     {"number": "64", "question": "Paid or been paid for a sexual act?"},
     {"number": "65", "question": "Committed an act of voyeurism?"},
     {"number": "66", "question": "Committed an act of incest?"},
     {"number": "67", "question": "Engaged in bestiality?"},
     {"number": "68", "question": "Ingested alcohol in a non-religious context?"},
     {"number": "69", "question": "Have you ever done a 69?"}, {"number": "70", "question": "Been drunk?"},
     {"number": "71", "question": "Faked sobriety in front of parents or teachers?"},
     {"number": "72", "question": "Had severe memory loss due to alcohol?"},
     {"number": "73", "question": "Used tobacco?"}, {"number": "74", "question": "Used marijuana?"},
     {"number": "75", "question": "Used a drug stronger than marijuana?"},
     {"number": "76", "question": "Used methamphetamine, crack, cocaine, PCP, horse tranquilizers or heroin?"},
     {"number": "77",
      "question": "Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?"},
     {"number": "78", "question": "Been put on disciplinary probation or suspended?"},
     {"number": "79", "question": "Urinated in front of anyone?"}, {"number": "80", "question": "Urinated in public?"},
     {"number": "81", "question": "Taken a shower/bath with anyone older than 10 years of age?"},
     {"number": "82", "question": "Gone skinny-dipping?"},
     {"number": "83", "question": "Gone streaking (running naked through a public place)?"},
     {"number": "84", "question": "Seen a stripper?"}, {"number": "85", "question": "Had the police called on you?"},
     {"number": "86", "question": "Run from the police?"}, {"number": "87", "question": "Had the police question you?"},
     {"number": "88", "question": "Got handcuffed?"}, {"number": "89", "question": "Been arrested?"},
     {"number": "90", "question": "Been convicted of a crime?"},
     {"number": "91", "question": "Been convicted of a felony?"},
     {"number": "92", "question": "Committed an act of vandalism?"},
     {"number": "93",
      "question": "Joined themile high club?The mile high club (is slang for the group of people who have had sexual intercourse on board an aircraft in flight)."},
     {"number": "94",
      "question": "Participated in a booty call with a partner whom you were not in a relationship with?"},
     {"number": "95", "question": "Traveled 100 miles or more for the primary purpose of sexual intercourse?"},
     {"number": "96", "question": "Had sexual intercourse with a partner with an age gap of more than 3 years?"},
     {"number": "97", "question": "Had sexual intercourse with a virgin?"},
     {"number": "98", "question": "Had sexual intercourse without a condom?"},
     {"number": "99", "question": "Had an STD (sexually transmitted disease) test due to reasonable suspicion?"},
     {"number": "100", "question": "Had an STD?"}
]


responses = [
 {
  "score": 90,
  "response": "Aaaaaah, it's not easy!!! Don't mind this spoilt brats oooh!!! Don't follow their own ways. Do you!!",
 },

 {
  "score": 75,
  "response": "Omoh! You have spoil sha👀. Anyways you still have a chance, just try eeehn. Stay away from bad things, maybe, just maybe, you can change.",
 },

 {
  "score": 50,
  "response": ".................GUY!!!!!!!!!!!!!!!!, AAAAAAAHHHHHH!!!!!!!!!!. Calm down oooh the last time i checked heaven was still real oooh!!!!"
 },

 {
  "score": 25,
  "response": "Go to google maps, hit the search bar, type in 'Churches nearby', because GUY!!! How!!! AAAAHH!!!!!"
 },

 {
  "score": 15,
  "response": "On the day of judgement, please don't bother staying in line. Just start falling down. Don't delay the rest of us. Thank you.  "
 }


]

